pipeline {
    agent any

    environment {
        STAGING_SERVER_IP = '18.207.188.70'
        STAGING_USER = 'ubuntu'
        REMOTE_APP_DIR = '/home/ubuntu/App'
    }

    stages {
        stage('Env Setup') {
            steps {
                dir('Python_Web_App') {
                    withCredentials([
                        string(credentialsId: 'mongo-uri', variable: 'MONGO_URI'),
                        string(credentialsId: 'secret-key', variable: 'SECRET_KEY')
                    ]) {
                        sh '''
                        echo "Injecting environment variables into .env..."
                        cat <<EOF > .env
                        MONGO_URI=$MONGO_URI
                        SECRET_KEY=$SECRET_KEY
                        EOF
                        '''
                    }
                }
            }
        }
        stage('Build') {
            steps {
                echo 'Installing the dependencies...'
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                cd Python_Web_App/
                pip install -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'Testing the application...'
                sh '''
                . venv/bin/activate
                cd Python_Web_App/
                pytest || true
                '''
            }
        }
        stage('Deploy') {
            steps {
                sshagent (['staging-pem-key']) {
                    echo 'Copying the files to the staging server...'
                    sh '''
                    ssh -o StrictHostKeyChecking=no $STAGING_USER@$STAGING_SERVER_IP "mkdir -p $REMOTE_APP_DIR"
                    scp -o StrictHostKeyChecking=no -r Python_Web_App/* $STAGING_USER@$STAGING_SERVER_IP:$REMOTE_APP_DIR/
                    '''

                    echo 'Running the application...'
                    sh '''
                    cd $REMOTE_APP_DIR/
                    ls -la $REMOTE_APP_DIR
                    // cd $REMOTE_APP_DIR/Python_Web_App
                    sudo apt update && sudo apt install -y python3-venv python3-pip
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    BUILD_ID=dontKillMe nohup python3 app.py > output.log 2>&1 &
                    '''
                }
            }
        }
    }
}
