pipeline {
    agent any

    stages {
        stage('Build') {
            echo 'Installing the dependencies...'
            sh 'pip install -r requirements.txt'
        }
        stage('Test') {
            echo 'Testing the application...'
            sh 'pytest || true'
        }
        stage('Deploy') {
            echo 'Deploying the application...'
            sh 'python3 app.py'
        }
    }
}