pipeline {
    agent any

    environment {
        STAGING_SERVER_IP = '44.202.251.153'
        STAGING_USER = 'ubuntu'
        REMOTE_APP_DIR = '/home/ubuntu/App'
    }

    stages {
        stage('Env Setup') {
            steps {
                dir('Python_Web_App') {
                    withCredentials([
                        string(credentialsId: 'mongo-uri', variable: 'MONGO_URI'),
                        string(credentialsId: 'secret-key', variable: 'SECRET_KEY')
                    ]) {
                        sh '''
                        echo "Injecting environment variables into .env..."
                        cat <<EOF > .env
                        MONGO_URI=$MONGO_URI
                        SECRET_KEY=$SECRET_KEY
                        EOF
                        '''
                    }
                }
            }
        }
        stage('Build') {
            steps {
                echo 'Installing the dependencies...'
                sh '''
                cd Python_Web_App/
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'Testing the application...'
                sh '''
                cd Python_Web_App/
                . venv/bin/activate
                pytest || true
                '''
            }
        }
        stage('Deploy') {
            steps {
                sshagent (['staging_pem_key']) {
                    withCredentials([
                        string(credentialsId: 'mongo-uri', variable: 'MONGO_URI'),
                        string(credentialsId: 'secret-key', variable: 'SECRET_KEY')
                    ]) {
                        sh """
                        ssh -o StrictHostKeyChecking=no $STAGING_USER@$STAGING_SERVER_IP "
                        cd $REMOTE_APP_DIR && ls -la && \

                        echo \\"MONGO_URI=${MONGO_URI}\\" > .env && \
                        echo \\"SECRET_KEY=${SECRET_KEY}\\" >> .env && \

                        python3 -m venv venv && \
                        . venv/bin/activate && \
                        pip install -r requirements.txt && \

                        sudo systemctl restart myapp
                        "
                        """
                    }
                }
            }
        }
    }
}
